# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [32]:
import numpy as np
arr=np.random.uniform(0,20,7)
arr=arr/np.linalg.norm(arr)
arr

array([0.28064613, 0.31482534, 0.26283767, 0.44798558, 0.64411139,
       0.35909879, 0.09228546])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [39]:
matrix=np.array([[np.random.randint(11) for i in range(10)] for i in range(8)])
matrix
m=10**5
for i in range(8):
    t=sum(matrix[i,:])
    if t<m:
        m=t
        r=i
print(m,matrix[r,:])

32 [0 0 4 2 7 0 7 4 0 8]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [40]:
a,b=np.array([0,0]),np.array([5,3])
np.linalg.norm(a-b)

5.830951894845301

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [44]:
a=np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
b=np.array([[3, -1], [2, 1]])
c=np.array([[7, 21], [11, 8], [8, 4]])
np.linalg.inv(a)
np.linalg.inv(a)@(-c)@np.linalg.inv(b)

array([[ 1.00000000e+00,  1.02140518e-15],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [29]:
import numpy as np
df=np.loadtxt("minutes_n_ingredients.csv",dtype="int32",delimiter=",",skiprows=1)
df[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [3]:
print("mean:",df[:,1:].mean(axis=0))
print("min:",df[:,1:].min(axis=0))
print("max:",df[:,1:].max(axis=0))
print("med:",np.median(df[:, 1:], axis=0))

среднее: [2.16010017e+04 9.05528000e+00]
минимум: [0 1]
максимум: [2147483647         39]
медиана: [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [4]:
q=np.quantile(df[:,1],.75,axis=0)
print("квантиль:",q)
arr_=df[:,1]<q
df=df[arr_]
df

квантиль: 65.0


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [371794,     35,      8],
       [ 43407,     35,      7],
       [370915,      5,      4]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [5]:
print(len(np.where(df[:,1]==0)[0]))
df[df[:,1]==0]=1
df

479


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [371794,     35,      8],
       [ 43407,     35,      7],
       [370915,      5,      4]])

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [6]:
len(np.unique(df[:,0]))

72628

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [7]:
len(np.unique(df[:,2])),np.unique(df[:,2])

(32,
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 33, 34]))

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [8]:
df_1=df[df[:,2]<=5]
df_1

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [25]:
max(df[:,2] / df[:,1])

23.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [12]:
df[df[:,1]].argsort()[-100:,2].mean(axis=0)

0.0

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [15]:
df[[np.random.choice(np.arange(len(df))) for i in  range(10)]]

array([[412980,      5,      5],
       [170753,     50,     14],
       [344419,     30,     13],
       [ 65567,     21,      6],
       [176500,     40,      9],
       [289471,     15,      9],
       [ 80342,     20,      8],
       [386183,     45,     15],
       [ 54530,     15,      4],
       [187949,     20,     11]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [16]:
mn=df[:,2].mean()
dflm=df[df[:,2]<mn]
len(dflm)/len(df)*100

53.29795092058107

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [20]:
df2=np.hstack([df,np.zeros(len(df)).reshape(len(df),1)])
df2[:,3]=(df[:,1]<=20)&(df[:,2]<=5)
df2

array([[1.27244e+05, 6.00000e+01, 1.60000e+01, 0.00000e+00],
       [2.38910e+04, 2.50000e+01, 7.00000e+00, 0.00000e+00],
       [9.47460e+04, 1.00000e+01, 6.00000e+00, 0.00000e+00],
       ...,
       [3.71794e+05, 3.50000e+01, 8.00000e+00, 0.00000e+00],
       [4.34070e+04, 3.50000e+01, 7.00000e+00, 0.00000e+00],
       [3.70915e+05, 5.00000e+00, 4.00000e+00, 1.00000e+00]])

13. Выведите процент "простых" рецептов в датасете

In [24]:
df2[:,3].sum()/len(df2)*100

13.60079884004049

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [23]:
short = df[df[:,1]<10]
st = df[(df[:,1]>10)&(df[:,1]<20)]
long = df[df[:,1]>=20]
dim = min(len(short), len(st), len(long))
arr = np.stack([short[:dim], st[:dim], long[:dim]])
arr.shape

(3, 7588, 3)